### ISSUE TITLE
增加对DYNAMIC_TYPE_NONE的渲染支持

### ISSUE THREAD

**Issue by blyc** [Polyisoprene/DynamicRender#29]
![图片](https://user-images.githubusercontent.com/34291620/227872902-98cfcc03-e78f-4489-bace-7c0d7b50242f.png)
大佬你好，请问类似这种转发动态（DYNAMIC_TYPE_FORWARD）的源动态已删除（DYNAMIC_TYPE_NONE），能否在渲染时加上类似【源动态已删除】的文本提示呢？目前v1.1.9使用发现是 return None 所以渲染图中没有任何表现，会显得有些怪异。
例图动态id：567663727278579035

**Comment by Polyisoprene** [comment]
> ![图片](https://user-images.githubusercontent.com/34291620/227872902-98cfcc03-e78f-4489-bace-7c0d7b50242f.png) 大佬你好，请问类似这种转发动态（DYNAMIC_TYPE_FORWARD）的源动态已删除（DYNAMIC_TYPE_NONE），能否在渲染时加上类似【源动态已删除】的文本提示呢？目前v1.1.9使用发现是 return None 所以渲染图中没有任何表现，会显得有些怪异。 例图动态id：567663727278579035

可以加，以前是为了保证最快的渲染出图所以舍弃了一些不必要的东西

**Comment by Polyisoprene** [comment]
已经更新了此功能
